### ISSUE TITLE
Top and Right 3D print files seem to be swapped

### ISSUE THREAD

**Issue by wrljet** [skiselev/micro_8088_case#1]
Sergey,

The 3D files for the Top and Right seem to be swapped, contents vs. the names.

Bill

**Comment by skiselev** [comment]
Hi Bill,

I guess it depends how do you place the case. The parts are named as if the case was laying down on the "bottom", that is the side where the backplane is attached.
Of course the way I took the picture, the top becomes left, and the right becomes top, etc. Everything is rotated 90 degrees counterclockwise.

Let me know if I missed something here.

Thanks,
Sergey

**Comment by wrljet** [comment]
OK, I understand now.  That explains a few other questions I had.

Bill
