### ISSUE TITLE
Dead link to Intel Front Panel Pinout

### ISSUE THREAD

**Issue by wrljet** [skiselev/micro_8088_case#2]
Sergey, the link to the Intel Front Panel Pinout in the README appears to be dead.

I found this [page](https://www.intel.com/content/www/us/en/support/articles/000007309/intel-nuc.html?wapkw=front%20panel%20pinout), which shows the 9-pin (10 with a key) pinout you're using.

You have to expand the little dropdown doodad though on the page to see the 9-pin diagram.

Bill

**Comment by skiselev** [comment]
Fixed. Also added the BOM for the front panel cables, in case people want to build their own instead of using ready made female jumper cables
